# Generated by Django 5.2.4 on 2025-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='certification_number',
            field=models.CharField(max_length=100),
        ),
    ]
