# Generated by Django 5.2.4 on 2025-08-16 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_client_certification_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], help_text='Previous certification status', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], help_text='New certification status', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the status change', null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Clients.client')),
            ],
            options={
                'verbose_name': 'Client Status History',
                'verbose_name_plural': 'Client Status Histories',
                'db_table': 'client_status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['client', 'changed_at'], name='client_stat_client__cdc66f_idx'), models.Index(fields=['new_status', 'changed_at'], name='client_stat_new_sta_32e6e7_idx'), models.Index(fields=['changed_at'], name='client_stat_changed_ddbb67_idx')],
            },
        ),
    ]
