# Generated by Django 5.2.4 on 2025-08-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_clientstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text="Client's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text="Client's phone number", max_length=20, null=True),
        ),
    ]
