# Generated by Django 5.2.4 on 2025-08-17 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('mobile', models.CharField(help_text="Customer's mobile number", max_length=20)),
                ('subject', models.CharField(help_text='Subject of the enquiry', max_length=500)),
                ('message', models.TextField(help_text='Detailed message from customer')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the enquiry', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True, help_text='Response from admin/staff', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the response was sent', null=True)),
            ],
            options={
                'verbose_name': 'Customer Enquiry',
                'verbose_name_plural': 'Customer Enquiries',
                'db_table': 'enquiry',
                'ordering': ['-created_at'],
            },
        ),
    ]
